### ISSUE TITLE
aguardando as configuraçoes 

### ISSUE THREAD

**Issue by abelbinu** [DaniloAgostinho/essencias-comandos-linux#1]
@DaniloAgostinho 

danilo estou esperando os arquivos para correçao

**Comment by DaniloAgostinho** [comment]
@abelbinu 

Já recebi as suas alterações aqui, grato pela correção.

:+1:

**Comment by DaniloAgostinho** [comment]
@abelbinu 

Já recebi as suas alterações aqui, grato pela correção.

:+1:

**Comment by DaniloAgostinho** [comment]
@Eidi199 

Lembra o que conversamos sobre não divulgar nomes em repositórios? 

:-1:  

:)
